_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.0
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
architecture:
    value: Simple-UNET
dataset:
    value: MATLAB
epochs:
    value: 10
learning_rate:
    value: 0.001
